### ISSUE TITLE
Missing manifest.json file when I tried to compile...

### ISSUE THREAD

**Issue by gricelsepulveda** [naitian/Swish#1]
All is compiling successfully but when I try to install, Chrome answer for a manifest.json file Maybe I've missing something?

**Comment by naitian** [comment]
Hi Gricel, unfortunately, this extension no longer works because Dribbble has updated its API to remove these endpoints.

**Comment by gricelsepulveda** [comment]
Ok. I found the last version of the dribbble new tab extension in a chrome folder from an older PC. I leave you a link to download. You can use it by "load unpacked extension" option in the chrome extensions manager ; ) 

thanks anyway, bye!

https://drive.google.com/file/d/1iJRGn_GCUzsbufKjzhKICb2VjgnApwB6/view?usp=sharing

**Comment by Sanabria** [comment]
@naitian Sorry to hear but also it would be great to add that notice to the readme? I wasted some time trying to figure out what was wrong while building it

**Comment by naitian** [comment]
Hi Sanabria, currently the first line fo the readme reads: "Deprecated since the new Dribbble API. This extension no longer works. 😢"

**Comment by Sanabria** [comment]
My bad. I don't know how I missed it!
